config/routes.rb
Rails.application.routes.draw do
  	devise_for :users, controllers: {
        registrations: 'users/registrations'
      }, path: '',path_names: { sign_up: 'sign_up', sign_in: 'sign_in'}

    resources :users, only: [:show, :update ]
	resources :images, only: [:new, :create, :destroy] do
		collection do
			post 'favourite_toggle'
		end
	end
	resources :documents, only: [:new, :create, :destroy] do
		collection do
			post 'favourite_toggle'
		end
	end
	resources :sounds, only: [:new, :create, :destroy] do
		collection do
			post 'favourite_toggle'
		end
	end
	resources :videos, only: [:new, :create, :destroy] do
		collection do
			post 'favourite_toggle'
		end
	end
	resources :services, only: [:new, :create, :destroy] do
		collection do
		end
	end
	# resources :pages, only: [] do
	# 	collection do
	# 		get 'contact'
	# 		get 'index'
	# 		get 'about'
	# 		get 'pay'
	# 		get 'therapist'
	# 		get 'galleryWithGrid'
	# 		get 'galleryWithOutGrid'
	# 	end
	# end

    get '/contact',         to: 'pages#contact'
    get '/about',           to: 'pages#about'
    get '/pay',             to: 'pages#pay'
    get '/index',           to: 'pages#index'
    get 'profile',          to: 'pages#profile'
    get '/dashboard',       to: 'pages#dashboard'
    get '/home',            to: 'pages#home'
    get '/adminpanel',      to: 'pages#adminpanel'
    get '/users',           to: 'pages#users'
    get '/therapists',      to: 'pages#therapists'
    get '/galleryWithGrid', to: 'pages#galleryWithGrid'
    get '/galleryWithOutGrid', to: 'pages#galleryWithOutGrid'
    get '/checkout',        to: 'pages#checkout'
    get '/auction',         to: 'posts#auction'

    post '/card_pay', to: 'stripe#card_pay'
    post '/send_email', to: 'email#send_email'

  	devise_scope :user do
  	  authenticated :user do
  	    root 'pages#dashboard', as: :authenticated_root
  	  end
  	  unauthenticated do
  	    root 'pages#home', as: :unauthenticated_root
  	    # root 'devise/sessions#new', as: :unauthenticated_root
  	  end
    end
    resources :posts
    resources :categories do
    	member do
    		get 'get_sub_categories' 
    	end
    end
    resources :sub_categories
    resources :brands
    resources :types
    resources :tags
    resources :provinces
    resources :cities
    resources :addresses
    resources :payment_methods
    resources :orders do
    collection do 
      post 'buy_auction_product'
      end
    end
    resources :bids
    resources :carts do 
      collection do 
        post 'add_products'
        delete 'delete_products'

      end
    end

end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :tags
  has_and_belongs_to_many :sub_categories
  has_and_belongs_to_many :brands
  has_many :posts

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController


  def show
    @category = Category.find(params[:id])

  end

  def edit
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.present?
      @category.destroy
    end
    redirect_to categories_path
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
			flash[:success] = "Category is successfully updated"
			redirect_to categories_path
  end

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def get_sub_categories
     @category = Category.find_by_id(params[:id])
     @sub_categories = @category.sub_categories
     @brands = @category.brands
  end
  
  def create
    @category = Category.new(category_params)
    	# @article.user= current_user
    	if @category.save
    		flash[:success] = "Category is successfully created"
    	    redirect_to new_category_path(@categories)
    	else
    		render 'new'
    	end
  end

  def category_params
    	params.require(:category).permit(:name)
  end
end

app/views/categories/edit.html.erb
<div class= 'row'>
	<div class='col-xs-12'>
		<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f|%>
		<div class= "form-group">
			<%= f.label :name%>
			<%= f.text_field :name, class: "form-control", placeholder: "Name of the Category", autofocus: true %>
		</div>

		<div class="form-group">
			<%= f.submit class:'btn btn-primary btn-lg'%>
		</div>

		<% end %>
	</div>
</div>

app/views/categories/get_sub_categories.js.erb
$('#subcategories').empty().append("<option value = ''>Choose a Sub category</option>");
$('#subcategories').append("<%= escape_javascript options_from_collection_for_select(@sub_categories, :id, :name) %>");

$('#brands').empty().append("<option value = ''>Choose a Brand</option>");
$('#brands').append("<%= escape_javascript options_from_collection_for_select(@brands, :id, :name) %>");

app/views/categories/index.html.erb
<h1 align="center"> Welcome to Categories Page </h1><br><br><br>

  <div class="row" align="center" >
    <td><%= link_to('Create New Category', new_category_path , method: :get, class: "btn btn-large btn-primary")%></td>

  </div>

<div id="categories" class="tab-pane">
    <div class="table-responsive">
      <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>Id</th>
          <th>Name</th>
          <th>Action</th>
        </tr>
      </thead>

      <tbody>
        <% @categories.each_with_index do |category,index| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td>
              <%= link_to('Edit', edit_category_path(category), class: "btn btn-large btn-primary")%>
              <%= link_to('Delete', category_path(category), method: :delete, class: "btn btn-large btn-primary")%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

app/views/categories/new.html.erb
<div class= 'row'>
	<div class='col-xs-12'>
		<%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f|%>
		<div class= "form-group">
			<%= f.label :name%>
			<%= f.text_field :name, class: "form-control", placeholder: "Name of the Category", autofocus: true %>
		</div>

		<div class="form-group">
			<%= f.submit class:'btn btn-primary btn-lg'%>
		</div>

		<% end %>
	</div>
</div>

app/views/categories/show.html.erb
<br><h1 style="text-align:center;"></h1>
<!-- banner-bootom-w3-agileits -->
<div class="banner-bootom-w3-agileits">
	<div class="container">
		<!-- mens -->
		<div class="col-md-4 products-left">
			
			<div class="css-treeview col-md-10">
				<h4>Categories</h4>
				<ul class="tree-list-pad">
					<%Category.all.each_with_index do |category,cat_index|%>
					<li><input type="checkbox" checked="checked" id="item-<%=cat_index%>" /><label for="item-<%=cat_index%>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i> <%=category.name%></label>
						<ul>
							<%category.sub_categories.each_with_index do |sub_category,sub_index|%>
							<li>
								<input type="checkbox" id="item-<%=cat_index%>-<%=sub_index%>" /><label for="item-<%=cat_index%>-<%=sub_index%>"><i class="fa fa-long-arrow-right" aria-hidden="true"></i><%= link_to sub_category.name, sub_category_path(sub_category.id)%></label>
							
							</li>
							<%end%>
						</ul>
					</li>
					<%end%>
				</ul>
			</div>
		</div>
		<div class="col-md-8 products-right">
			<%@category.posts.each_with_index do |post,post_index|%>
				<div class="col-md-4 product-men">
					<div class="men-pro-item simpleCart_shelfItem">
						<div class="men-thumb-item">
							<%= image_tag post.photo_url, class: "pro-image-front"%>
							<%= image_tag post.photo_url, class: "pro-image-back"%>
							<div class="men-cart-pro">
								<div class="inner-men-cart-pro link-product-add-cart"">
									<%= link_to "Quick View", post_path(post) %>
								</div>
							</div>
							<span class="product-new-top">New</span>
						</div>
						<div class="item-info-product ">
							<h4><a href="single.html"><%=post.name.first(20)%></a></h4>
							<div class="info-product-price">
								<span class="item_price"><%=post.price%></span>
							</div>
							<div class="snipcart-details top_brand_home_details item_add single-item hvr-outline-out button2">
						        <form action="/carts/add_products" method="post">
						            <fieldset>
						                <input type="hidden" name="amount" value="1" />
						                <input type="hidden" name="post_id" value="<%=post.id%>" />
						                <input type="submit" name="submit" value="Add to cart" class="button" />
						                
						            </fieldset>
						        </form>
						    </div>

						</div>
					</div>
				</div>
			<%end%>
		</div>
		<div class="clearfix"></div>
	</div>
</div>